#ifndef _Z3_RTSP_ERROR_HPP_
#define _Z3_RTSP_ERROR_HPP_

enum Z3_RSTP_SYS_ERROR
{
        Z3_RTSP_SYS_BASE_ERROR = 0x80001000,
        Z3_RTSP_ENOTIMPL,
        Z3_RTSP_EPARSE,
        Z3_RTSP_EINTR,
        Z3_RTSP_EUNSUPPORTED,
        Z3_RTSP_EOUTOFPORTS,
        Z3_RTSP_ESTREAMCOUNTS,
        Z3_RTSP_EMEDIASESSION,
        Z3_RTSP_ENOSESSIONID,
        Z3_RTSP_ESESSIONID
};

enum Z3_RTSP_SESSION_ERROR
{
        Z3_RTSP_SESSION_BASE_ERROR = 0x90001000,
        Z3_RTSP_SESSION_ECONNECT
};
#endif